name: splatco
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3
  - plyfile
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm
  - dacite
  - kornia
  - wandb
  - ipdb
  - matplotlib
  - point_cloud_utils
  - laspy
  - einops=0.6.1
  - jaxtyping
  - pip:
    - submodules/simple-knn
    - submodules/diff-gaussian-rasterization #Rendering
    - submodules/gridcreater #Context
    - submodules/gridencoder #Context
    - scikit-learn
    - zCurve #tri-piane
    - pillow_heif #tri-piane
    - opencv-contrib-python #tri-piane
    - torch-scatter #tri-piane
